on:
  schedule:
    - cron:  '0 0 * * 1,2,3,4,5'

jobs:
  build_docker_image:
    name: "Call build and push action"
    uses: ./.github/workflows/test--receive-input-output.yml
    secrets: inherit
    with:
      image-name: workflow.transition.monitor
      image-tag: nightly
